// Generated from “LV20N visca.xlsx”, sheet “01 Visca”, rows 6–143.
// Do not hand-edit command packets; update the workbook extraction generator instead.

import type { Lv20nCommandGroup } from './lv20n-types.js'

export const lv20nCommandGroups = [
	{
		id: 'address_set',
		name: 'Address setting',
		commands: [
			{
				workbookRow: 6,
				id: 'r6',
				groupId: 'address_set',
				groupName: 'Address setting',
				name: 'Broadcast',
				bytes: [136, 48, 1, 255],
				parameters: [],
				description: 'Address setting',
			},
		],
	},
	{
		id: 'power',
		name: 'Power',
		commands: [
			{
				workbookRow: 7,
				id: 'r7',
				groupId: 'power',
				groupName: 'Power',
				name: 'On',
				bytes: [129, 1, 4, 0, 2, 255],
				parameters: [],
				description: 'Power ON/OFF',
			},
			{
				workbookRow: 8,
				id: 'r8',
				groupId: 'power',
				groupName: 'Power',
				name: 'Off',
				bytes: [129, 1, 4, 0, 3, 255],
				parameters: [],
				description: '',
			},
		],
	},
	{
		id: 'zoom',
		name: 'Zoom',
		commands: [
			{
				workbookRow: 9,
				id: 'r9',
				groupId: 'zoom',
				groupName: 'Zoom',
				name: 'Stop',
				bytes: [129, 1, 4, 7, 0, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 10,
				id: 'r10',
				groupId: 'zoom',
				groupName: 'Zoom',
				name: 'Tele(Standard)',
				bytes: [129, 1, 4, 7, 2, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 11,
				id: 'r11',
				groupId: 'zoom',
				groupName: 'Zoom',
				name: 'Wide(Standard)',
				bytes: [129, 1, 4, 7, 3, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 12,
				id: 'r12',
				groupId: 'zoom',
				groupName: 'Zoom',
				name: 'Tele(Variable)',
				bytes: [129, 1, 4, 7, 32, 255],
				parameters: [
					{
						id: 'speed',
						label: 'Tele zoom speed',
						min: 0,
						max: 7,
						nibbles: [9],
						default: 3,
					},
				],
				description: 'p=0 (Low) to 7 (High)',
			},
			{
				workbookRow: 13,
				id: 'r13',
				groupId: 'zoom',
				groupName: 'Zoom',
				name: 'Wide(Variable)',
				bytes: [129, 1, 4, 7, 48, 255],
				parameters: [
					{
						id: 'speed',
						label: 'Wide zoom speed',
						min: 0,
						max: 7,
						nibbles: [9],
						default: 3,
					},
				],
				description: '',
			},
			{
				workbookRow: 14,
				id: 'r14',
				groupId: 'zoom',
				groupName: 'Zoom',
				name: 'Direct',
				bytes: [129, 1, 4, 71, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'position',
						label: 'Zoom position',
						min: 0,
						max: 16384,
						nibbles: [9, 11, 13, 15],
						default: 0,
					},
				],
				description: 'pqrs: Zoom Position(0x0000~0x4000)',
			},
		],
	},
	{
		id: 'digital_zoom',
		name: 'Digital zoom',
		commands: [
			{
				workbookRow: 15,
				id: 'r15',
				groupId: 'digital_zoom',
				groupName: 'Digital zoom',
				name: 'ON',
				bytes: [129, 1, 4, 6, 2, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 16,
				id: 'r16',
				groupId: 'digital_zoom',
				groupName: 'Digital zoom',
				name: 'OFF',
				bytes: [129, 1, 4, 6, 3, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 17,
				id: 'r17',
				groupId: 'digital_zoom',
				groupName: 'Digital zoom',
				name: 'DZoomLimit',
				bytes: [129, 1, 4, 38, 0, 255],
				parameters: [
					{
						id: 'limit',
						label: 'Digital zoom limit (0 = x1, 15 = x16)',
						min: 0,
						max: 15,
						nibbles: [9],
						default: 0,
					},
				],
				description: 'p= 1~16(x1~x16)',
			},
		],
	},
	{
		id: 'focus',
		name: 'Focus',
		commands: [
			{
				workbookRow: 18,
				id: 'r18',
				groupId: 'focus',
				groupName: 'Focus',
				name: 'Stop',
				bytes: [129, 1, 4, 8, 0, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 19,
				id: 'r19',
				groupId: 'focus',
				groupName: 'Focus',
				name: 'Far(Standard)',
				bytes: [129, 1, 4, 8, 2, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 20,
				id: 'r20',
				groupId: 'focus',
				groupName: 'Focus',
				name: 'Near(Standard)',
				bytes: [129, 1, 4, 8, 3, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 21,
				id: 'r21',
				groupId: 'focus',
				groupName: 'Focus',
				name: 'Far(Variable)',
				bytes: [129, 1, 4, 8, 32, 255],
				parameters: [
					{
						id: 'speed',
						label: 'Far focus speed',
						min: 0,
						max: 7,
						nibbles: [9],
						default: 3,
					},
				],
				description: 'p=0 (Low) to 7 (High)',
			},
			{
				workbookRow: 22,
				id: 'r22',
				groupId: 'focus',
				groupName: 'Focus',
				name: 'Near(Variable)',
				bytes: [129, 1, 4, 8, 48, 255],
				parameters: [
					{
						id: 'speed',
						label: 'Near focus speed',
						min: 0,
						max: 7,
						nibbles: [9],
						default: 3,
					},
				],
				description: '',
			},
			{
				workbookRow: 23,
				id: 'r23',
				groupId: 'focus',
				groupName: 'Focus',
				name: 'Direct',
				bytes: [129, 1, 4, 72, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'position',
						label: 'Focus position',
						min: 12224,
						max: 17024,
						nibbles: [9, 11, 13, 15],
						default: 12224,
					},
				],
				description: 'pqrs: Focus Position(0x2FC0~0x4280)',
			},
			{
				workbookRow: 24,
				id: 'r24',
				groupId: 'focus',
				groupName: 'Focus',
				name: 'Auto Focus',
				bytes: [129, 1, 4, 56, 2, 255],
				parameters: [],
				description: 'AF ON/OFF',
			},
			{
				workbookRow: 25,
				id: 'r25',
				groupId: 'focus',
				groupName: 'Focus',
				name: 'Manual Focus',
				bytes: [129, 1, 4, 56, 3, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 26,
				id: 'r26',
				groupId: 'focus',
				groupName: 'Focus',
				name: 'Auto/Manual',
				bytes: [129, 1, 4, 56, 16, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 27,
				id: 'r27',
				groupId: 'focus',
				groupName: 'Focus',
				name: 'One Push Trigger',
				bytes: [129, 1, 4, 24, 1, 255],
				parameters: [],
				description: 'One Push AF Trigger(Effective in manual mode )',
			},
		],
	},
	{
		id: 'zoom_focus',
		name: 'Zoom and focus',
		commands: [
			{
				workbookRow: 28,
				id: 'r28',
				groupId: 'zoom_focus',
				groupName: 'Zoom and focus',
				name: 'Direct',
				bytes: [129, 1, 4, 71, 0, 0, 0, 0, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'zoom_position',
						label: 'Zoom position',
						min: 0,
						max: 16384,
						nibbles: [9, 11, 13, 15],
						default: 0,
					},
					{
						id: 'focus_position',
						label: 'Focus position',
						min: 12224,
						max: 17024,
						nibbles: [17, 19, 21, 23],
						default: 12224,
					},
				],
				description: 'pqrs: Zoom Position(0x0000~0x4000) tuvw: Focus Position(0x2FC0~0x4280)',
			},
		],
	},
	{
		id: 'white_balance',
		name: 'White balance',
		commands: [
			{
				workbookRow: 29,
				id: 'r29',
				groupId: 'white_balance',
				groupName: 'White balance',
				name: 'Auto',
				bytes: [129, 1, 4, 53, 0, 255],
				parameters: [],
				description: 'Normal Auto',
			},
			{
				workbookRow: 30,
				id: 'r30',
				groupId: 'white_balance',
				groupName: 'White balance',
				name: 'One Push WB',
				bytes: [129, 1, 4, 53, 3, 255],
				parameters: [],
				description: 'One Push WB mode',
			},
			{
				workbookRow: 31,
				id: 'r31',
				groupId: 'white_balance',
				groupName: 'White balance',
				name: 'ATW',
				bytes: [129, 1, 4, 53, 4, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 32,
				id: 'r32',
				groupId: 'white_balance',
				groupName: 'White balance',
				name: 'Manual',
				bytes: [129, 1, 4, 53, 5, 255],
				parameters: [],
				description: 'Manual Control mode',
			},
			{
				workbookRow: 33,
				id: 'r33',
				groupId: 'white_balance',
				groupName: 'White balance',
				name: 'One push trigger',
				bytes: [129, 1, 4, 16, 5, 255],
				parameters: [],
				description: 'One Push WB Trigger(Effective in One Push mode)',
			},
			{
				workbookRow: 34,
				id: 'r34',
				groupId: 'white_balance',
				groupName: 'White balance',
				name: 'Color Temperature',
				bytes: [129, 1, 4, 53, 11, 255],
				parameters: [],
				description: 'Color_Temperature mode',
			},
		],
	},
	{
		id: 'white_balance_color_temperature',
		name: 'White balance color temperature',
		commands: [
			{
				workbookRow: 35,
				id: 'r35',
				groupId: 'white_balance_color_temperature',
				groupName: 'White balance color temperature',
				name: 'Direct',
				bytes: [129, 1, 14, 36, 73, 0, 0, 255],
				parameters: [
					{
						id: 'level',
						label: 'Color temperature (2800K + level × 100K)',
						min: 0,
						max: 37,
						nibbles: [11, 13],
						default: 16,
					},
				],
				description: 'pq:Color_Temperature Level pq = 00h to 25h 0x00~0x25:2800~6500',
			},
		],
	},
	{
		id: 'manual_red_gain',
		name: 'Manual white balance red gain',
		commands: [
			{
				workbookRow: 36,
				id: 'r36',
				groupId: 'manual_red_gain',
				groupName: 'Manual white balance red gain',
				name: 'Reset',
				bytes: [129, 1, 4, 3, 0, 255],
				parameters: [],
				description: 'Manual Control of R Gain',
			},
			{
				workbookRow: 37,
				id: 'r37',
				groupId: 'manual_red_gain',
				groupName: 'Manual white balance red gain',
				name: 'Up',
				bytes: [129, 1, 4, 3, 2, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 38,
				id: 'r38',
				groupId: 'manual_red_gain',
				groupName: 'Manual white balance red gain',
				name: 'Down',
				bytes: [129, 1, 4, 3, 3, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 39,
				id: 'r39',
				groupId: 'manual_red_gain',
				groupName: 'Manual white balance red gain',
				name: 'Direct',
				bytes: [129, 1, 4, 67, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'gain',
						label: 'Manual red gain',
						min: 0,
						max: 16,
						nibbles: [13, 15],
						default: 8,
					},
				],
				description: 'pq: R Gain (0x00~0x10) example:p = 1,q = 0, pq = 0x10 , Value = 16;',
			},
		],
	},
	{
		id: 'manual_blue_gain',
		name: 'Manual white balance blue gain',
		commands: [
			{
				workbookRow: 40,
				id: 'r40',
				groupId: 'manual_blue_gain',
				groupName: 'Manual white balance blue gain',
				name: 'Reset',
				bytes: [129, 1, 4, 4, 0, 255],
				parameters: [],
				description: 'Manual Control of B Gain',
			},
			{
				workbookRow: 41,
				id: 'r41',
				groupId: 'manual_blue_gain',
				groupName: 'Manual white balance blue gain',
				name: 'Up',
				bytes: [129, 1, 4, 4, 2, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 42,
				id: 'r42',
				groupId: 'manual_blue_gain',
				groupName: 'Manual white balance blue gain',
				name: 'Down',
				bytes: [129, 1, 4, 4, 3, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 43,
				id: 'r43',
				groupId: 'manual_blue_gain',
				groupName: 'Manual white balance blue gain',
				name: 'Direct',
				bytes: [129, 1, 4, 68, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'gain',
						label: 'Manual blue gain',
						min: 0,
						max: 16,
						nibbles: [13, 15],
						default: 8,
					},
				],
				description: 'pq: B Gain(0x00~0x10) example:p = 1,q = 0, pq = 0x10 , Value = 16;',
			},
		],
	},
	{
		id: 'automatic_red_gain',
		name: 'Automatic white balance red gain',
		commands: [
			{
				workbookRow: 44,
				id: 'r44',
				groupId: 'automatic_red_gain',
				groupName: 'Automatic white balance red gain',
				name: 'Direct',
				bytes: [129, 1, 14, 36, 70, 0, 0, 255],
				parameters: [
					{
						id: 'gain',
						label: 'Automatic red gain',
						min: 0,
						max: 14,
						nibbles: [11, 13],
						default: 7,
					},
				],
				description: 'pq:Auto_WB RGain pq = 00h to 0Eh Auto Control of R Gain',
			},
		],
	},
	{
		id: 'automatic_blue_gain',
		name: 'Automatic white balance blue gain',
		commands: [
			{
				workbookRow: 45,
				id: 'r45',
				groupId: 'automatic_blue_gain',
				groupName: 'Automatic white balance blue gain',
				name: 'Direct',
				bytes: [129, 1, 14, 36, 71, 0, 0, 255],
				parameters: [
					{
						id: 'gain',
						label: 'Automatic blue gain',
						min: 0,
						max: 14,
						nibbles: [11, 13],
						default: 7,
					},
				],
				description: 'pq:Auto_WB BGain pq = 00h to 0Eh Auto Control of B Gain',
			},
		],
	},
	{
		id: 'automatic_green_gain',
		name: 'Automatic white balance green gain',
		commands: [
			{
				workbookRow: 46,
				id: 'r46',
				groupId: 'automatic_green_gain',
				groupName: 'Automatic white balance green gain',
				name: 'Direct',
				bytes: [129, 1, 14, 36, 72, 0, 0, 255],
				parameters: [
					{
						id: 'gain',
						label: 'Automatic green gain',
						min: 0,
						max: 14,
						nibbles: [11, 13],
						default: 7,
					},
				],
				description: 'pq:Auto_WB GGain pq = 00h to 0Eh Auto Control of G Gain',
			},
		],
	},
	{
		id: 'exposure_mode',
		name: 'Exposure mode',
		commands: [
			{
				workbookRow: 47,
				id: 'r47',
				groupId: 'exposure_mode',
				groupName: 'Exposure mode',
				name: 'Full Auto',
				bytes: [129, 1, 4, 57, 0, 255],
				parameters: [],
				description: 'Automatic Exposure mode',
			},
			{
				workbookRow: 48,
				id: 'r48',
				groupId: 'exposure_mode',
				groupName: 'Exposure mode',
				name: 'Manual',
				bytes: [129, 1, 4, 57, 3, 255],
				parameters: [],
				description: 'Manual Control mode',
			},
			{
				workbookRow: 49,
				id: 'r49',
				groupId: 'exposure_mode',
				groupName: 'Exposure mode',
				name: 'Shutter Priority',
				bytes: [129, 1, 4, 57, 10, 255],
				parameters: [],
				description: 'Shutter Priority Automatic Exposure mode',
			},
			{
				workbookRow: 50,
				id: 'r50',
				groupId: 'exposure_mode',
				groupName: 'Exposure mode',
				name: 'Iris Priority',
				bytes: [129, 1, 4, 57, 11, 255],
				parameters: [],
				description: 'Iris Priority Automatic Exposure mode',
			},
			{
				workbookRow: 51,
				id: 'r51',
				groupId: 'exposure_mode',
				groupName: 'Exposure mode',
				name: 'Bright',
				bytes: [129, 1, 4, 57, 13, 255],
				parameters: [],
				description: 'Bright Mode (Manual control)',
			},
			{
				workbookRow: 52,
				id: 'r52',
				groupId: 'exposure_mode',
				groupName: 'Exposure mode',
				name: 'GainLimit',
				bytes: [129, 1, 4, 44, 0, 255],
				parameters: [
					{
						id: 'limit',
						label: 'Gain limit index (12–45 dB in 3 dB steps)',
						min: 4,
						max: 15,
						nibbles: [9],
						default: 15,
					},
				],
				description:
					'Gain Limit Setting in AE mode (Full Auto, Shutter priority, Iris priority, Spot light) 0p: Limit Gain Position  p:0x04~0x0F(12dB~45dB) The interval is 3dB',
			},
		],
	},
	{
		id: 'shutter',
		name: 'Shutter',
		commands: [
			{
				workbookRow: 53,
				id: 'r53',
				groupId: 'shutter',
				groupName: 'Shutter',
				name: 'Reset',
				bytes: [129, 1, 4, 10, 0, 255],
				parameters: [],
				description: 'Shutter Setting',
			},
			{
				workbookRow: 54,
				id: 'r54',
				groupId: 'shutter',
				groupName: 'Shutter',
				name: 'Up',
				bytes: [129, 1, 4, 10, 2, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 55,
				id: 'r55',
				groupId: 'shutter',
				groupName: 'Shutter',
				name: 'Down',
				bytes: [129, 1, 4, 10, 3, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 56,
				id: 'r56',
				groupId: 'shutter',
				groupName: 'Shutter',
				name: 'Direct',
				bytes: [129, 1, 4, 74, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'position',
						label: 'Shutter position',
						min: 6,
						max: 21,
						nibbles: [13, 15],
						default: 8,
					},
				],
				description:
					'pq: Shutter Position(0x06~0x15) 0x06~0x15 :1/60~1/10000 example:p = 1 , q = 5 , pq = 0x15 ，Value = 21',
			},
		],
	},
	{
		id: 'iris',
		name: 'Iris',
		commands: [
			{
				workbookRow: 57,
				id: 'r57',
				groupId: 'iris',
				groupName: 'Iris',
				name: 'Reset',
				bytes: [129, 1, 4, 11, 0, 255],
				parameters: [],
				description: 'Iris Setting',
			},
			{
				workbookRow: 58,
				id: 'r58',
				groupId: 'iris',
				groupName: 'Iris',
				name: 'Up',
				bytes: [129, 1, 4, 11, 2, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 59,
				id: 'r59',
				groupId: 'iris',
				groupName: 'Iris',
				name: 'Down',
				bytes: [129, 1, 4, 11, 3, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 60,
				id: 'r60',
				groupId: 'iris',
				groupName: 'Iris',
				name: 'Direct',
				bytes: [129, 1, 4, 75, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'position',
						label: 'Iris position',
						min: 0,
						max: 13,
						nibbles: [13, 15],
						default: 8,
					},
				],
				description: 'pq: Iris Position(0x00~0x0D) example:p = 0 , q = D , pq = 0x0D ，Value = 13',
			},
		],
	},
	{
		id: 'gain',
		name: 'Gain',
		commands: [
			{
				workbookRow: 61,
				id: 'r61',
				groupId: 'gain',
				groupName: 'Gain',
				name: 'Reset',
				bytes: [129, 1, 4, 12, 0, 255],
				parameters: [],
				description: 'Gain Setting',
			},
			{
				workbookRow: 62,
				id: 'r62',
				groupId: 'gain',
				groupName: 'Gain',
				name: 'Up',
				bytes: [129, 1, 4, 12, 2, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 63,
				id: 'r63',
				groupId: 'gain',
				groupName: 'Gain',
				name: 'Down',
				bytes: [129, 1, 4, 12, 3, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 64,
				id: 'r64',
				groupId: 'gain',
				groupName: 'Gain',
				name: 'Direct',
				bytes: [129, 1, 4, 76, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'position',
						label: 'Gain position',
						min: 0,
						max: 14,
						nibbles: [13, 15],
						default: 0,
					},
				],
				description: 'pq: Gain Position(0x00~0x0E) example:p = 0 , q = D , pq = 0x0E ，Value = 14',
			},
		],
	},
	{
		id: 'bright',
		name: 'Exposure brightness',
		commands: [
			{
				workbookRow: 65,
				id: 'r65',
				groupId: 'bright',
				groupName: 'Exposure brightness',
				name: 'Reset',
				bytes: [129, 1, 4, 13, 0, 255],
				parameters: [],
				description: 'Bright Setting',
			},
			{
				workbookRow: 66,
				id: 'r66',
				groupId: 'bright',
				groupName: 'Exposure brightness',
				name: 'Up',
				bytes: [129, 1, 4, 13, 2, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 67,
				id: 'r67',
				groupId: 'bright',
				groupName: 'Exposure brightness',
				name: 'Down',
				bytes: [129, 1, 4, 13, 3, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 68,
				id: 'r68',
				groupId: 'bright',
				groupName: 'Exposure brightness',
				name: 'Direct',
				bytes: [129, 1, 4, 77, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'position',
						label: 'Brightness position',
						min: 0,
						max: 27,
						nibbles: [13, 15],
						default: 13,
					},
				],
				description: 'pq: Bright Position(0x00~0x1B) example:p = 1 , q = B , pq = 0x1B ，Value = 27',
			},
		],
	},
	{
		id: 'exposure_compensation',
		name: 'Exposure compensation',
		commands: [
			{
				workbookRow: 69,
				id: 'r69',
				groupId: 'exposure_compensation',
				groupName: 'Exposure compensation',
				name: 'On',
				bytes: [129, 1, 4, 62, 2, 255],
				parameters: [],
				description: 'Exposure Compensation ON/OFF',
			},
			{
				workbookRow: 70,
				id: 'r70',
				groupId: 'exposure_compensation',
				groupName: 'Exposure compensation',
				name: 'Off',
				bytes: [129, 1, 4, 62, 3, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 71,
				id: 'r71',
				groupId: 'exposure_compensation',
				groupName: 'Exposure compensation',
				name: 'Reset',
				bytes: [129, 1, 4, 14, 0, 255],
				parameters: [],
				description: 'Exposure Compensation Amount Setting',
			},
			{
				workbookRow: 72,
				id: 'r72',
				groupId: 'exposure_compensation',
				groupName: 'Exposure compensation',
				name: 'Up',
				bytes: [129, 1, 4, 14, 2, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 73,
				id: 'r73',
				groupId: 'exposure_compensation',
				groupName: 'Exposure compensation',
				name: 'Down',
				bytes: [129, 1, 4, 14, 3, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 74,
				id: 'r74',
				groupId: 'exposure_compensation',
				groupName: 'Exposure compensation',
				name: 'Direct',
				bytes: [129, 1, 4, 78, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'position',
						label: 'Exposure compensation',
						min: 0,
						max: 14,
						nibbles: [13, 15],
						default: 7,
						choices: [
							{
								value: 0,
								label: '-7',
							},
							{
								value: 1,
								label: '-6',
							},
							{
								value: 2,
								label: '-5',
							},
							{
								value: 3,
								label: '-4',
							},
							{
								value: 4,
								label: '-3',
							},
							{
								value: 5,
								label: '-2',
							},
							{
								value: 6,
								label: '-1',
							},
							{
								value: 7,
								label: '0',
							},
							{
								value: 8,
								label: '1',
							},
							{
								value: 9,
								label: '2',
							},
							{
								value: 10,
								label: '3',
							},
							{
								value: 11,
								label: '4',
							},
							{
								value: 12,
								label: '5',
							},
							{
								value: 13,
								label: '6',
							},
							{
								value: 14,
								label: '7',
							},
						],
					},
				],
				description:
					'ExpComp Position 0q:0x00~0x0E(-7~+7) example:p = 0 , q = 0 , pq = 0x00 ，Value = -7 example:p = 0 , q = E , pq = 0x0E ，Value = +7',
			},
		],
	},
	{
		id: 'backlight',
		name: 'Backlight compensation',
		commands: [
			{
				workbookRow: 75,
				id: 'r75',
				groupId: 'backlight',
				groupName: 'Backlight compensation',
				name: 'On',
				bytes: [129, 1, 4, 51, 2, 255],
				parameters: [],
				description: 'Back Light Compensation ON/OFF',
			},
			{
				workbookRow: 76,
				id: 'r76',
				groupId: 'backlight',
				groupName: 'Backlight compensation',
				name: 'Off',
				bytes: [129, 1, 4, 51, 3, 255],
				parameters: [],
				description: '',
			},
		],
	},
	{
		id: 'aperture',
		name: 'Aperture',
		commands: [
			{
				workbookRow: 77,
				id: 'r77',
				groupId: 'aperture',
				groupName: 'Aperture',
				name: 'Reset',
				bytes: [129, 1, 4, 2, 0, 255],
				parameters: [],
				description: 'Aperture Control',
			},
			{
				workbookRow: 78,
				id: 'r78',
				groupId: 'aperture',
				groupName: 'Aperture',
				name: 'Up',
				bytes: [129, 1, 4, 2, 2, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 79,
				id: 'r79',
				groupId: 'aperture',
				groupName: 'Aperture',
				name: 'Down',
				bytes: [129, 1, 4, 2, 3, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 80,
				id: 'r80',
				groupId: 'aperture',
				groupName: 'Aperture',
				name: 'Direct',
				bytes: [129, 1, 4, 66, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'gain',
						label: 'Aperture gain',
						min: 0,
						max: 11,
						nibbles: [13, 15],
						default: 5,
					},
				],
				description: 'pq: Aperture Gain(0x00~0x0B) example:p = 0 , q = B , pq = 0x0B ，Value = 11',
			},
		],
	},
	{
		id: 'memory',
		name: 'Preset memory',
		commands: [
			{
				workbookRow: 81,
				id: 'r81',
				groupId: 'memory',
				groupName: 'Preset memory',
				name: 'Reset',
				bytes: [129, 1, 4, 63, 0, 0, 255],
				parameters: [
					{
						id: 'preset',
						label: 'Preset number',
						min: 0,
						max: 64,
						nibbles: [10, 11],
						default: 0,
					},
				],
				description: 'pp: Memory Number (=0 to 64)',
			},
			{
				workbookRow: 82,
				id: 'r82',
				groupId: 'memory',
				groupName: 'Preset memory',
				name: 'Set',
				bytes: [129, 1, 4, 63, 1, 0, 255],
				parameters: [
					{
						id: 'preset',
						label: 'Preset number',
						min: 0,
						max: 64,
						nibbles: [10, 11],
						default: 0,
					},
				],
				description: '',
			},
			{
				workbookRow: 83,
				id: 'r83',
				groupId: 'memory',
				groupName: 'Preset memory',
				name: 'Recall',
				bytes: [129, 1, 4, 63, 2, 0, 255],
				parameters: [
					{
						id: 'preset',
						label: 'Preset number',
						min: 0,
						max: 64,
						nibbles: [10, 11],
						default: 0,
					},
				],
				description: 'Corresponds to 0 to 64 on the Remote Commander.',
			},
		],
	},
	{
		id: 'ir_receive',
		name: 'IR receiver',
		commands: [
			{
				workbookRow: 84,
				id: 'r84',
				groupId: 'ir_receive',
				groupName: 'IR receiver',
				name: 'ON',
				bytes: [129, 1, 6, 8, 2, 255],
				parameters: [],
				description: 'IR(remote commander) receive ON/OFF',
			},
			{
				workbookRow: 85,
				id: 'r85',
				groupId: 'ir_receive',
				groupName: 'IR receiver',
				name: 'OFF',
				bytes: [129, 1, 6, 8, 3, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 86,
				id: 'r86',
				groupId: 'ir_receive',
				groupName: 'IR receiver',
				name: 'ON/OFF',
				bytes: [129, 1, 6, 8, 16, 255],
				parameters: [],
				description: '',
			},
		],
	},
	{
		id: 'video_system',
		name: 'Video format',
		commands: [
			{
				workbookRow: 87,
				id: 'r87',
				groupId: 'video_system',
				groupName: 'Video format',
				name: '60 HZ',
				bytes: [129, 1, 6, 53, 0, 0, 255],
				parameters: [],
				description: '1920 x1080p/60',
			},
			{
				workbookRow: 88,
				id: 'r88',
				groupId: 'video_system',
				groupName: 'Video format',
				name: '1920 x1080p',
				bytes: [129, 1, 6, 53, 0, 1, 255],
				parameters: [],
				description: '1920 x1080p/30Z',
			},
			{
				workbookRow: 89,
				id: 'r89',
				groupId: 'video_system',
				groupName: 'Video format',
				name: '1280 x720p',
				bytes: [129, 1, 6, 53, 0, 3, 255],
				parameters: [],
				description: '1280 x720p/60',
			},
			{
				workbookRow: 90,
				id: 'r90',
				groupId: 'video_system',
				groupName: 'Video format',
				name: '50 HZ',
				bytes: [129, 1, 6, 53, 0, 8, 255],
				parameters: [],
				description: '1920 x1080p/50',
			},
			{
				workbookRow: 91,
				id: 'r91',
				groupId: 'video_system',
				groupName: 'Video format',
				name: '1920 x1080p',
				bytes: [129, 1, 6, 53, 0, 9, 255],
				parameters: [],
				description: '1920 x1080p/25',
			},
			{
				workbookRow: 92,
				id: 'r92',
				groupId: 'video_system',
				groupName: 'Video format',
				name: '1280 x720p',
				bytes: [129, 1, 6, 53, 0, 11, 255],
				parameters: [],
				description: '1280 x720p/50',
			},
			{
				workbookRow: 93,
				id: 'r93',
				groupId: 'video_system',
				groupName: 'Video format',
				name: '1280 x720p',
				bytes: [129, 1, 6, 53, 0, 12, 255],
				parameters: [],
				description: '1280 x720p/25',
			},
			{
				workbookRow: 94,
				id: 'r94',
				groupId: 'video_system',
				groupName: 'Video format',
				name: '59.94/29.97',
				bytes: [129, 1, 6, 53, 0, 16, 255],
				parameters: [],
				description: '1920 x1080p/59.94',
			},
			{
				workbookRow: 95,
				id: 'r95',
				groupId: 'video_system',
				groupName: 'Video format',
				name: '1920 x1080p',
				bytes: [129, 1, 6, 53, 0, 17, 255],
				parameters: [],
				description: '1920 x1080p/29.97',
			},
			{
				workbookRow: 96,
				id: 'r96',
				groupId: 'video_system',
				groupName: 'Video format',
				name: '1280 x720p',
				bytes: [129, 1, 6, 53, 0, 18, 255],
				parameters: [],
				description: '1280 x720p/59.94',
			},
		],
	},
	{
		id: 'pan_tilt',
		name: 'Pan and tilt',
		commands: [
			{
				workbookRow: 97,
				id: 'r97',
				groupId: 'pan_tilt',
				groupName: 'Pan and tilt',
				name: 'Up',
				bytes: [129, 1, 6, 1, 0, 0, 3, 1, 255],
				parameters: [
					{
						id: 'pan_speed',
						label: 'Pan speed',
						min: 1,
						max: 24,
						nibbles: [8, 9],
						default: 12,
					},
					{
						id: 'tilt_speed',
						label: 'Tilt speed',
						min: 1,
						max: 20,
						nibbles: [10, 11],
						default: 12,
					},
				],
				description: 'VV: Pan speed 0 x01 (low speed) to 0 x18 (high speed)',
			},
			{
				workbookRow: 98,
				id: 'r98',
				groupId: 'pan_tilt',
				groupName: 'Pan and tilt',
				name: 'Down',
				bytes: [129, 1, 6, 1, 0, 0, 3, 2, 255],
				parameters: [
					{
						id: 'pan_speed',
						label: 'Pan speed',
						min: 1,
						max: 24,
						nibbles: [8, 9],
						default: 12,
					},
					{
						id: 'tilt_speed',
						label: 'Tilt speed',
						min: 1,
						max: 20,
						nibbles: [10, 11],
						default: 12,
					},
				],
				description: '',
			},
			{
				workbookRow: 99,
				id: 'r99',
				groupId: 'pan_tilt',
				groupName: 'Pan and tilt',
				name: 'Left',
				bytes: [129, 1, 6, 1, 0, 0, 1, 3, 255],
				parameters: [
					{
						id: 'pan_speed',
						label: 'Pan speed',
						min: 1,
						max: 24,
						nibbles: [8, 9],
						default: 12,
					},
					{
						id: 'tilt_speed',
						label: 'Tilt speed',
						min: 1,
						max: 20,
						nibbles: [10, 11],
						default: 12,
					},
				],
				description: 'WW: Tilt Speed 0 x 01 (low speed) to 0 x14 (high speed)',
			},
			{
				workbookRow: 100,
				id: 'r100',
				groupId: 'pan_tilt',
				groupName: 'Pan and tilt',
				name: 'Right',
				bytes: [129, 1, 6, 1, 0, 0, 2, 3, 255],
				parameters: [
					{
						id: 'pan_speed',
						label: 'Pan speed',
						min: 1,
						max: 24,
						nibbles: [8, 9],
						default: 12,
					},
					{
						id: 'tilt_speed',
						label: 'Tilt speed',
						min: 1,
						max: 20,
						nibbles: [10, 11],
						default: 12,
					},
				],
				description: '',
			},
			{
				workbookRow: 101,
				id: 'r101',
				groupId: 'pan_tilt',
				groupName: 'Pan and tilt',
				name: 'UpLeft',
				bytes: [129, 1, 6, 1, 0, 0, 1, 1, 255],
				parameters: [
					{
						id: 'pan_speed',
						label: 'Pan speed',
						min: 1,
						max: 24,
						nibbles: [8, 9],
						default: 12,
					},
					{
						id: 'tilt_speed',
						label: 'Tilt speed',
						min: 1,
						max: 20,
						nibbles: [10, 11],
						default: 12,
					},
				],
				description: 'YYYY: Pan Position ZZZZ: Tilt Position',
			},
			{
				workbookRow: 102,
				id: 'r102',
				groupId: 'pan_tilt',
				groupName: 'Pan and tilt',
				name: 'UpRight',
				bytes: [129, 1, 6, 1, 0, 0, 2, 1, 255],
				parameters: [
					{
						id: 'pan_speed',
						label: 'Pan speed',
						min: 1,
						max: 24,
						nibbles: [8, 9],
						default: 12,
					},
					{
						id: 'tilt_speed',
						label: 'Tilt speed',
						min: 1,
						max: 20,
						nibbles: [10, 11],
						default: 12,
					},
				],
				description: '',
			},
			{
				workbookRow: 103,
				id: 'r103',
				groupId: 'pan_tilt',
				groupName: 'Pan and tilt',
				name: 'DownLeft',
				bytes: [129, 1, 6, 1, 0, 0, 1, 2, 255],
				parameters: [
					{
						id: 'pan_speed',
						label: 'Pan speed',
						min: 1,
						max: 24,
						nibbles: [8, 9],
						default: 12,
					},
					{
						id: 'tilt_speed',
						label: 'Tilt speed',
						min: 1,
						max: 20,
						nibbles: [10, 11],
						default: 12,
					},
				],
				description: '',
			},
			{
				workbookRow: 104,
				id: 'r104',
				groupId: 'pan_tilt',
				groupName: 'Pan and tilt',
				name: 'DownRight',
				bytes: [129, 1, 6, 1, 0, 0, 2, 2, 255],
				parameters: [
					{
						id: 'pan_speed',
						label: 'Pan speed',
						min: 1,
						max: 24,
						nibbles: [8, 9],
						default: 12,
					},
					{
						id: 'tilt_speed',
						label: 'Tilt speed',
						min: 1,
						max: 20,
						nibbles: [10, 11],
						default: 12,
					},
				],
				description: '',
			},
			{
				workbookRow: 105,
				id: 'r105',
				groupId: 'pan_tilt',
				groupName: 'Pan and tilt',
				name: 'Stop',
				bytes: [129, 1, 6, 1, 0, 0, 3, 3, 255],
				parameters: [
					{
						id: 'pan_speed',
						label: 'Pan speed',
						min: 1,
						max: 24,
						nibbles: [8, 9],
						default: 12,
					},
					{
						id: 'tilt_speed',
						label: 'Tilt speed',
						min: 1,
						max: 20,
						nibbles: [10, 11],
						default: 12,
					},
				],
				description: '',
			},
			{
				workbookRow: 106,
				id: 'r106',
				groupId: 'pan_tilt',
				groupName: 'Pan and tilt',
				name: 'AbsolutePosition',
				bytes: [129, 1, 6, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'pan_speed',
						label: 'Pan speed',
						min: 1,
						max: 24,
						nibbles: [8, 9],
						default: 12,
					},
					{
						id: 'tilt_speed',
						label: 'Tilt speed',
						min: 1,
						max: 20,
						nibbles: [10, 11],
						default: 12,
					},
					{
						id: 'pan_position',
						label: 'Pan position',
						min: 0,
						max: 65535,
						nibbles: [13, 15, 17, 19],
						default: 0,
					},
					{
						id: 'tilt_position',
						label: 'Tilt position',
						min: 0,
						max: 65535,
						nibbles: [21, 23, 25, 27],
						default: 0,
					},
				],
				description: '',
			},
			{
				workbookRow: 107,
				id: 'r107',
				groupId: 'pan_tilt',
				groupName: 'Pan and tilt',
				name: 'RelativePosition',
				bytes: [129, 1, 6, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'pan_speed',
						label: 'Pan speed',
						min: 1,
						max: 24,
						nibbles: [8, 9],
						default: 12,
					},
					{
						id: 'tilt_speed',
						label: 'Tilt speed',
						min: 1,
						max: 20,
						nibbles: [10, 11],
						default: 12,
					},
					{
						id: 'pan_offset',
						label: 'Pan offset',
						min: 0,
						max: 65535,
						nibbles: [13, 15, 17, 19],
						default: 0,
					},
					{
						id: 'tilt_offset',
						label: 'Tilt offset',
						min: 0,
						max: 65535,
						nibbles: [21, 23, 25, 27],
						default: 0,
					},
				],
				description: '',
			},
			{
				workbookRow: 108,
				id: 'r108',
				groupId: 'pan_tilt',
				groupName: 'Pan and tilt',
				name: 'Home',
				bytes: [129, 1, 6, 4, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 109,
				id: 'r109',
				groupId: 'pan_tilt',
				groupName: 'Pan and tilt',
				name: 'Reset',
				bytes: [129, 1, 6, 5, 255],
				parameters: [],
				description: '',
			},
		],
	},
	{
		id: 'audio_volume',
		name: 'Audio volume',
		commands: [
			{
				workbookRow: 110,
				id: 'r110',
				groupId: 'audio_volume',
				groupName: 'Audio volume',
				name: 'Reset',
				bytes: [129, 1, 4, 110, 0, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 111,
				id: 'r111',
				groupId: 'audio_volume',
				groupName: 'Audio volume',
				name: 'Up',
				bytes: [129, 1, 4, 110, 2, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 112,
				id: 'r112',
				groupId: 'audio_volume',
				groupName: 'Audio volume',
				name: 'Down',
				bytes: [129, 1, 4, 110, 3, 255],
				parameters: [],
				description: '',
			},
			{
				workbookRow: 113,
				id: 'r113',
				groupId: 'audio_volume',
				groupName: 'Audio volume',
				name: 'Direct',
				bytes: [129, 1, 4, 110, 1, 0, 0, 255],
				parameters: [
					{
						id: 'volume',
						label: 'Audio volume',
						min: 0,
						max: 100,
						nibbles: [11, 13],
						default: 50,
					},
				],
				description: 'pq:Audio Volume pq:0x00~0x64',
			},
		],
	},
	{
		id: 'sharpness',
		name: 'Image sharpness',
		commands: [
			{
				workbookRow: 114,
				id: 'r114',
				groupId: 'sharpness',
				groupName: 'Image sharpness',
				name: 'Direct',
				bytes: [129, 1, 14, 36, 64, 0, 0, 255],
				parameters: [
					{
						id: 'value',
						label: 'Sharpness',
						min: 0,
						max: 11,
						nibbles: [11, 13],
						default: 5,
					},
				],
				description: 'pq: Sharpness value pq = 00h to 0Bh',
			},
		],
	},
	{
		id: 'brightness',
		name: 'Image brightness',
		commands: [
			{
				workbookRow: 115,
				id: 'r115',
				groupId: 'brightness',
				groupName: 'Image brightness',
				name: 'Direct',
				bytes: [129, 1, 14, 36, 65, 0, 0, 255],
				parameters: [
					{
						id: 'value',
						label: 'Brightness',
						min: 0,
						max: 14,
						nibbles: [11, 13],
						default: 7,
					},
				],
				description: 'pq: Bright value pq = 00h to 0Eh',
			},
		],
	},
	{
		id: 'contrast',
		name: 'Image contrast',
		commands: [
			{
				workbookRow: 116,
				id: 'r116',
				groupId: 'contrast',
				groupName: 'Image contrast',
				name: 'Direct',
				bytes: [129, 1, 14, 36, 66, 0, 0, 255],
				parameters: [
					{
						id: 'value',
						label: 'Contrast',
						min: 0,
						max: 14,
						nibbles: [11, 13],
						default: 7,
					},
				],
				description: 'pq: Contrast value pq = 00h to 0Eh',
			},
		],
	},
	{
		id: 'saturation',
		name: 'Image saturation',
		commands: [
			{
				workbookRow: 117,
				id: 'r117',
				groupId: 'saturation',
				groupName: 'Image saturation',
				name: 'Direct',
				bytes: [129, 1, 14, 36, 67, 0, 0, 255],
				parameters: [
					{
						id: 'value',
						label: 'Saturation',
						min: 0,
						max: 14,
						nibbles: [11, 13],
						default: 7,
					},
				],
				description: 'pq: Saturation value pq = 00h to 0Eh',
			},
		],
	},
	{
		id: 'hue',
		name: 'Image hue',
		commands: [
			{
				workbookRow: 118,
				id: 'r118',
				groupId: 'hue',
				groupName: 'Image hue',
				name: 'Direct',
				bytes: [129, 1, 14, 36, 68, 0, 0, 255],
				parameters: [
					{
						id: 'value',
						label: 'Hue',
						min: 0,
						max: 14,
						nibbles: [11, 13],
						default: 7,
					},
				],
				description: 'pq: Hue value pq = 00h to 0Eh',
			},
		],
	},
	{
		id: 'noise_reduction_2d',
		name: '2D noise reduction',
		commands: [
			{
				workbookRow: 119,
				id: 'r119',
				groupId: 'noise_reduction_2d',
				groupName: '2D noise reduction',
				name: 'Direct',
				bytes: [129, 1, 4, 83, 0, 255],
				parameters: [
					{
						id: 'value',
						label: '2D noise reduction',
						min: 0,
						max: 7,
						nibbles: [9],
						default: 3,
					},
				],
				description: 'pq: 2DNR value p = 00h to 07h',
			},
		],
	},
	{
		id: 'noise_reduction_3d',
		name: '3D noise reduction',
		commands: [
			{
				workbookRow: 120,
				id: 'r120',
				groupId: 'noise_reduction_3d',
				groupName: '3D noise reduction',
				name: 'Direct',
				bytes: [129, 1, 4, 84, 0, 255],
				parameters: [
					{
						id: 'value',
						label: '3D noise reduction',
						min: 0,
						max: 7,
						nibbles: [9],
						default: 3,
					},
				],
				description: 'pq: 3DNR value p = 00h to 07h',
			},
		],
	},
	{
		id: 'gamma',
		name: 'Gamma',
		commands: [
			{
				workbookRow: 121,
				id: 'r121',
				groupId: 'gamma',
				groupName: 'Gamma',
				name: 'Direct',
				bytes: [129, 1, 4, 91, 0, 255],
				parameters: [
					{
						id: 'value',
						label: 'Gamma',
						min: 0,
						max: 4,
						nibbles: [9],
						default: 2,
					},
				],
				description: 'pq: Gamma value p = 00h to 04h',
			},
		],
	},
	{
		id: 'wdr',
		name: 'Wide dynamic range',
		commands: [
			{
				workbookRow: 122,
				id: 'r122',
				groupId: 'wdr',
				groupName: 'Wide dynamic range',
				name: 'Direct',
				bytes: [129, 1, 4, 61, 0, 255],
				parameters: [
					{
						id: 'value',
						label: 'Wide dynamic range',
						min: 0,
						max: 5,
						nibbles: [9],
						default: 0,
					},
				],
				description: 'pq: WDR value p = 00h to 05h',
			},
		],
	},
	{
		id: 'mirror',
		name: 'Mirror',
		commands: [
			{
				workbookRow: 123,
				id: 'r123',
				groupId: 'mirror',
				groupName: 'Mirror',
				name: 'Direct',
				bytes: [129, 1, 4, 97, 0, 255],
				parameters: [
					{
						id: 'state',
						label: 'Mirror',
						min: 2,
						max: 3,
						nibbles: [9],
						default: 3,
						choices: [
							{
								value: 2,
								label: 'On',
							},
							{
								value: 3,
								label: 'Off',
							},
						],
					},
				],
				description: 'p: 2(ON) 3(OFF)',
			},
		],
	},
	{
		id: 'flip',
		name: 'Flip',
		commands: [
			{
				workbookRow: 124,
				id: 'r124',
				groupId: 'flip',
				groupName: 'Flip',
				name: 'Direct',
				bytes: [129, 1, 4, 102, 0, 255],
				parameters: [
					{
						id: 'state',
						label: 'Flip',
						min: 2,
						max: 3,
						nibbles: [9],
						default: 3,
						choices: [
							{
								value: 2,
								label: 'On',
							},
							{
								value: 3,
								label: 'Off',
							},
						],
					},
				],
				description: 'p: 2(ON) 3(OFF)',
			},
		],
	},
	{
		id: 'anti_flicker',
		name: 'Anti-flicker',
		commands: [
			{
				workbookRow: 125,
				id: 'r125',
				groupId: 'anti_flicker',
				groupName: 'Anti-flicker',
				name: 'Direct',
				bytes: [129, 1, 4, 58, 0, 255],
				parameters: [
					{
						id: 'mode',
						label: 'Anti-flicker mode',
						min: 0,
						max: 2,
						nibbles: [9],
						default: 0,
						choices: [
							{
								value: 0,
								label: 'Off',
							},
							{
								value: 1,
								label: '50 Hz',
							},
							{
								value: 2,
								label: '60 Hz',
							},
						],
					},
				],
				description: 'p: 0(OFF) 1(50Hz) 2(60Hz) AE_mode in AUTO and Bri Pri',
			},
		],
	},
	{
		id: 'dhcp',
		name: 'Network DHCP',
		commands: [
			{
				workbookRow: 126,
				id: 'r126',
				groupId: 'dhcp',
				groupName: 'Network DHCP',
				name: 'On',
				bytes: [129, 1, 8, 8, 2, 255],
				parameters: [],
				description: 'DHCP ON',
			},
			{
				workbookRow: 127,
				id: 'r127',
				groupId: 'dhcp',
				groupName: 'Network DHCP',
				name: 'Off',
				bytes: [129, 1, 8, 8, 3, 255],
				parameters: [],
				description: 'DHCP OFF',
			},
		],
	},
	{
		id: 'ip_address',
		name: 'Network IP address',
		commands: [
			{
				workbookRow: 128,
				id: 'r128',
				groupId: 'ip_address',
				groupName: 'Network IP address',
				name: 'ab:hexadecimal value of first IP address value cd:hexadecimal value of second IP address value ef:hexadecimal value of third IP address value gh:hexadecimal value of fourth IP address value',
				bytes: [129, 1, 8, 7, 1, 0, 0, 0, 0, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'octet_1',
						label: 'IP address octet 1',
						min: 0,
						max: 255,
						nibbles: [11, 13],
						default: 192,
					},
					{
						id: 'octet_2',
						label: 'IP address octet 2',
						min: 0,
						max: 255,
						nibbles: [15, 17],
						default: 168,
					},
					{
						id: 'octet_3',
						label: 'IP address octet 3',
						min: 0,
						max: 255,
						nibbles: [19, 21],
						default: 1,
					},
					{
						id: 'octet_4',
						label: 'IP address octet 4',
						min: 0,
						max: 255,
						nibbles: [23, 25],
						default: 100,
					},
				],
				description:
					'ab:hexadecimal value of first IP address value cd:hexadecimal value of second IP address value ef:hexadecimal value of third IP address value gh:hexadecimal value of fourth IP address value',
			},
		],
	},
	{
		id: 'ip_mask',
		name: 'Network subnet mask',
		commands: [
			{
				workbookRow: 129,
				id: 'r129',
				groupId: 'ip_mask',
				groupName: 'Network subnet mask',
				name: 'ab:hexadecimal value of first IP mask value cd:hexadecimal value of second IP mask value ef:hexadecimal value of third IP mask value gh:hexadecimal value of fourth IP mask value',
				bytes: [129, 1, 8, 7, 2, 0, 0, 0, 0, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'octet_1',
						label: 'Subnet mask octet 1',
						min: 0,
						max: 255,
						nibbles: [11, 13],
						default: 255,
					},
					{
						id: 'octet_2',
						label: 'Subnet mask octet 2',
						min: 0,
						max: 255,
						nibbles: [15, 17],
						default: 255,
					},
					{
						id: 'octet_3',
						label: 'Subnet mask octet 3',
						min: 0,
						max: 255,
						nibbles: [19, 21],
						default: 255,
					},
					{
						id: 'octet_4',
						label: 'Subnet mask octet 4',
						min: 0,
						max: 255,
						nibbles: [23, 25],
						default: 0,
					},
				],
				description:
					'ab:hexadecimal value of first IP mask value cd:hexadecimal value of second IP mask value ef:hexadecimal value of third IP mask value gh:hexadecimal value of fourth IP mask value',
			},
		],
	},
	{
		id: 'ip_gateway',
		name: 'Network gateway',
		commands: [
			{
				workbookRow: 130,
				id: 'r130',
				groupId: 'ip_gateway',
				groupName: 'Network gateway',
				name: 'ab:hexadecimal value of first IP gateway value cd:hexadecimal value of second IP gateway value ef:hexadecimal value of third IP gateway value gh:hexadecimal value of fourth IP gateway value',
				bytes: [129, 1, 8, 7, 3, 0, 0, 0, 0, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'octet_1',
						label: 'Gateway octet 1',
						min: 0,
						max: 255,
						nibbles: [11, 13],
						default: 192,
					},
					{
						id: 'octet_2',
						label: 'Gateway octet 2',
						min: 0,
						max: 255,
						nibbles: [15, 17],
						default: 168,
					},
					{
						id: 'octet_3',
						label: 'Gateway octet 3',
						min: 0,
						max: 255,
						nibbles: [19, 21],
						default: 1,
					},
					{
						id: 'octet_4',
						label: 'Gateway octet 4',
						min: 0,
						max: 255,
						nibbles: [23, 25],
						default: 1,
					},
				],
				description:
					'ab:hexadecimal value of first IP gateway value cd:hexadecimal value of second IP gateway value ef:hexadecimal value of third IP gateway value gh:hexadecimal value of fourth IP gateway value',
			},
		],
	},
	{
		id: 'apply_ip',
		name: 'Apply network settings',
		commands: [
			{
				workbookRow: 131,
				id: 'r131',
				groupId: 'apply_ip',
				groupName: 'Apply network settings',
				name: 'Apply current IP DHCP, IP address,IP mask and IP gateway',
				bytes: [129, 1, 8, 7, 9, 255],
				parameters: [],
				description: 'Apply current IP DHCP, IP address,IP mask and IP gateway',
			},
		],
	},
	{
		id: 'factory_reset',
		name: 'Factory reset',
		commands: [
			{
				workbookRow: 132,
				id: 'r132',
				groupId: 'factory_reset',
				groupName: 'Factory reset',
				name: 'To restore factory settings',
				bytes: [129, 1, 4, 63, 3, 0, 255],
				parameters: [],
				description: 'To restore factory settings',
			},
		],
	},
	{
		id: 'system_menu',
		name: 'System menu',
		commands: [
			{
				workbookRow: 133,
				id: 'r133',
				groupId: 'system_menu',
				groupName: 'System menu',
				name: 'Direct',
				bytes: [129, 1, 6, 6, 16, 255],
				parameters: [],
				description: 'MENU ON/OFF',
			},
			{
				workbookRow: 134,
				id: 'r134',
				groupId: 'system_menu',
				groupName: 'System menu',
				name: 'ON',
				bytes: [129, 1, 6, 6, 2, 255],
				parameters: [],
				description: 'MENU ON',
			},
			{
				workbookRow: 135,
				id: 'r135',
				groupId: 'system_menu',
				groupName: 'System menu',
				name: 'OFF',
				bytes: [129, 1, 6, 6, 3, 255],
				parameters: [],
				description: 'MENU OFF',
			},
			{
				workbookRow: 136,
				id: 'r136',
				groupId: 'system_menu',
				groupName: 'System menu',
				name: 'ENTER',
				bytes: [129, 1, 4, 7, 2, 255],
				parameters: [],
				description: 'MENU ENTER',
			},
			{
				workbookRow: 137,
				id: 'r137',
				groupId: 'system_menu',
				groupName: 'System menu',
				name: 'RETURN',
				bytes: [129, 1, 4, 7, 3, 255],
				parameters: [],
				description: 'MENU RETURN',
			},
		],
	},
	{
		id: 'tally',
		name: 'Tally light',
		commands: [
			{
				workbookRow: 138,
				id: 'r138',
				groupId: 'tally',
				groupName: 'Tally light',
				name: 'Green On',
				bytes: [129, 1, 8, 0, 2, 255],
				parameters: [],
				description: '绿色（蓝色）常量（ON）',
			},
			{
				workbookRow: 139,
				id: 'r139',
				groupId: 'tally',
				groupName: 'Tally light',
				name: 'Red On',
				bytes: [129, 1, 8, 1, 2, 255],
				parameters: [],
				description: '红色常量（ON）',
			},
			{
				workbookRow: 140,
				id: 'r140',
				groupId: 'tally',
				groupName: 'Tally light',
				name: 'Green and Red All On',
				bytes: [129, 1, 8, 2, 2, 255],
				parameters: [],
				description: '红色、绿色同时常量（ON）',
			},
			{
				workbookRow: 141,
				id: 'r141',
				groupId: 'tally',
				groupName: 'Tally light',
				name: 'ALL OFF',
				bytes: [129, 1, 8, 2, 3, 255],
				parameters: [],
				description: '同时关闭Tally灯（OFF）',
			},
			{
				workbookRow: 142,
				id: 'r142',
				groupId: 'tally',
				groupName: 'Tally light',
				name: 'Green Flicker',
				bytes: [129, 1, 8, 16, 2, 255],
				parameters: [],
				description: '绿色（蓝色）闪烁（1次/s）',
			},
			{
				workbookRow: 143,
				id: 'r143',
				groupId: 'tally',
				groupName: 'Tally light',
				name: 'Red Flicker',
				bytes: [129, 1, 8, 17, 2, 255],
				parameters: [],
				description: '红色闪烁（1次/s）',
			},
		],
	},
] as const satisfies readonly Lv20nCommandGroup[]
