// Complete LV20N VISCA command catalog. Keep packet changes synchronized with the camera protocol specification.

import type { Lv20nCommandGroup } from './lv20n-types.js'

export const lv20nCommandGroups = [
	{
		id: 'address_set',
		name: 'Address setting',
		commands: [
			{
				id: 'r6',
				groupId: 'address_set',
				groupName: 'Address setting',
				name: 'Broadcast',
				bytes: [136, 48, 1, 255],
				parameters: [],
			},
		],
	},
	{
		id: 'power',
		name: 'Power',
		commands: [
			{
				id: 'r7',
				groupId: 'power',
				groupName: 'Power',
				name: 'On',
				bytes: [129, 1, 4, 0, 2, 255],
				parameters: [],
			},
			{
				id: 'r8',
				groupId: 'power',
				groupName: 'Power',
				name: 'Off',
				bytes: [129, 1, 4, 0, 3, 255],
				parameters: [],
			},
		],
	},
	{
		id: 'zoom',
		name: 'Zoom',
		commands: [
			{
				id: 'r9',
				groupId: 'zoom',
				groupName: 'Zoom',
				name: 'Stop',
				bytes: [129, 1, 4, 7, 0, 255],
				parameters: [],
			},
			{
				id: 'r10',
				groupId: 'zoom',
				groupName: 'Zoom',
				name: 'Tele (standard speed)',
				bytes: [129, 1, 4, 7, 2, 255],
				parameters: [],
			},
			{
				id: 'r11',
				groupId: 'zoom',
				groupName: 'Zoom',
				name: 'Wide (standard speed)',
				bytes: [129, 1, 4, 7, 3, 255],
				parameters: [],
			},
			{
				id: 'r12',
				groupId: 'zoom',
				groupName: 'Zoom',
				name: 'Tele (variable speed)',
				bytes: [129, 1, 4, 7, 32, 255],
				parameters: [
					{
						id: 'speed',
						label: 'Tele zoom speed',
						min: 0,
						max: 7,
						nibbles: [9],
						default: 3,
					},
				],
			},
			{
				id: 'r13',
				groupId: 'zoom',
				groupName: 'Zoom',
				name: 'Wide (variable speed)',
				bytes: [129, 1, 4, 7, 48, 255],
				parameters: [
					{
						id: 'speed',
						label: 'Wide zoom speed',
						min: 0,
						max: 7,
						nibbles: [9],
						default: 3,
					},
				],
			},
			{
				id: 'r14',
				groupId: 'zoom',
				groupName: 'Zoom',
				name: 'Direct',
				bytes: [129, 1, 4, 71, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'position',
						label: 'Zoom position',
						min: 0,
						max: 16384,
						nibbles: [9, 11, 13, 15],
						default: 0,
					},
				],
			},
		],
	},
	{
		id: 'digital_zoom',
		name: 'Digital zoom',
		commands: [
			{
				id: 'r15',
				groupId: 'digital_zoom',
				groupName: 'Digital zoom',
				name: 'ON',
				bytes: [129, 1, 4, 6, 2, 255],
				parameters: [],
			},
			{
				id: 'r16',
				groupId: 'digital_zoom',
				groupName: 'Digital zoom',
				name: 'OFF',
				bytes: [129, 1, 4, 6, 3, 255],
				parameters: [],
			},
			{
				id: 'r17',
				groupId: 'digital_zoom',
				groupName: 'Digital zoom',
				name: 'DZoomLimit',
				bytes: [129, 1, 4, 38, 0, 255],
				parameters: [
					{
						id: 'limit',
						label: 'Digital zoom limit (0 = x1, 15 = x16)',
						min: 0,
						max: 15,
						nibbles: [9],
						default: 0,
					},
				],
			},
		],
	},
	{
		id: 'focus',
		name: 'Focus',
		commands: [
			{
				id: 'r18',
				groupId: 'focus',
				groupName: 'Focus',
				name: 'Stop',
				bytes: [129, 1, 4, 8, 0, 255],
				parameters: [],
			},
			{
				id: 'r19',
				groupId: 'focus',
				groupName: 'Focus',
				name: 'Far (standard speed)',
				bytes: [129, 1, 4, 8, 2, 255],
				parameters: [],
			},
			{
				id: 'r20',
				groupId: 'focus',
				groupName: 'Focus',
				name: 'Near (standard speed)',
				bytes: [129, 1, 4, 8, 3, 255],
				parameters: [],
			},
			{
				id: 'r21',
				groupId: 'focus',
				groupName: 'Focus',
				name: 'Far (variable speed)',
				bytes: [129, 1, 4, 8, 32, 255],
				parameters: [
					{
						id: 'speed',
						label: 'Far focus speed',
						min: 0,
						max: 7,
						nibbles: [9],
						default: 3,
					},
				],
			},
			{
				id: 'r22',
				groupId: 'focus',
				groupName: 'Focus',
				name: 'Near (variable speed)',
				bytes: [129, 1, 4, 8, 48, 255],
				parameters: [
					{
						id: 'speed',
						label: 'Near focus speed',
						min: 0,
						max: 7,
						nibbles: [9],
						default: 3,
					},
				],
			},
			{
				id: 'r23',
				groupId: 'focus',
				groupName: 'Focus',
				name: 'Direct',
				bytes: [129, 1, 4, 72, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'position',
						label: 'Focus position',
						min: 12224,
						max: 17024,
						nibbles: [9, 11, 13, 15],
						default: 12224,
					},
				],
			},
			{
				id: 'r24',
				groupId: 'focus',
				groupName: 'Focus',
				name: 'Auto Focus',
				bytes: [129, 1, 4, 56, 2, 255],
				parameters: [],
			},
			{
				id: 'r25',
				groupId: 'focus',
				groupName: 'Focus',
				name: 'Manual Focus',
				bytes: [129, 1, 4, 56, 3, 255],
				parameters: [],
			},
			{
				id: 'r26',
				groupId: 'focus',
				groupName: 'Focus',
				name: 'Auto/Manual',
				bytes: [129, 1, 4, 56, 16, 255],
				parameters: [],
			},
			{
				id: 'r27',
				groupId: 'focus',
				groupName: 'Focus',
				name: 'One Push Trigger',
				bytes: [129, 1, 4, 24, 1, 255],
				parameters: [],
			},
		],
	},
	{
		id: 'zoom_focus',
		name: 'Zoom and focus',
		commands: [
			{
				id: 'r28',
				groupId: 'zoom_focus',
				groupName: 'Zoom and focus',
				name: 'Direct',
				bytes: [129, 1, 4, 71, 0, 0, 0, 0, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'zoom_position',
						label: 'Zoom position',
						min: 0,
						max: 16384,
						nibbles: [9, 11, 13, 15],
						default: 0,
					},
					{
						id: 'focus_position',
						label: 'Focus position',
						min: 12224,
						max: 17024,
						nibbles: [17, 19, 21, 23],
						default: 12224,
					},
				],
			},
		],
	},
	{
		id: 'white_balance',
		name: 'White balance',
		commands: [
			{
				id: 'r29',
				groupId: 'white_balance',
				groupName: 'White balance',
				name: 'Auto',
				bytes: [129, 1, 4, 53, 0, 255],
				parameters: [],
			},
			{
				id: 'r30',
				groupId: 'white_balance',
				groupName: 'White balance',
				name: 'One Push WB',
				bytes: [129, 1, 4, 53, 3, 255],
				parameters: [],
			},
			{
				id: 'r31',
				groupId: 'white_balance',
				groupName: 'White balance',
				name: 'ATW',
				bytes: [129, 1, 4, 53, 4, 255],
				parameters: [],
			},
			{
				id: 'r32',
				groupId: 'white_balance',
				groupName: 'White balance',
				name: 'Manual',
				bytes: [129, 1, 4, 53, 5, 255],
				parameters: [],
			},
			{
				id: 'r33',
				groupId: 'white_balance',
				groupName: 'White balance',
				name: 'One push trigger',
				bytes: [129, 1, 4, 16, 5, 255],
				parameters: [],
			},
			{
				id: 'r34',
				groupId: 'white_balance',
				groupName: 'White balance',
				name: 'Color Temperature',
				bytes: [129, 1, 4, 53, 11, 255],
				parameters: [],
			},
		],
	},
	{
		id: 'white_balance_color_temperature',
		name: 'White balance color temperature',
		commands: [
			{
				id: 'r35',
				groupId: 'white_balance_color_temperature',
				groupName: 'White balance color temperature',
				name: 'Direct',
				bytes: [129, 1, 14, 36, 73, 0, 0, 255],
				parameters: [
					{
						id: 'level',
						label: 'Color temperature (2800K + level × 100K)',
						min: 0,
						max: 37,
						nibbles: [11, 13],
						default: 16,
					},
				],
			},
		],
	},
	{
		id: 'manual_red_gain',
		name: 'Manual white balance red gain',
		commands: [
			{
				id: 'r36',
				groupId: 'manual_red_gain',
				groupName: 'Manual white balance red gain',
				name: 'Reset',
				bytes: [129, 1, 4, 3, 0, 255],
				parameters: [],
			},
			{
				id: 'r37',
				groupId: 'manual_red_gain',
				groupName: 'Manual white balance red gain',
				name: 'Up',
				bytes: [129, 1, 4, 3, 2, 255],
				parameters: [],
			},
			{
				id: 'r38',
				groupId: 'manual_red_gain',
				groupName: 'Manual white balance red gain',
				name: 'Down',
				bytes: [129, 1, 4, 3, 3, 255],
				parameters: [],
			},
			{
				id: 'r39',
				groupId: 'manual_red_gain',
				groupName: 'Manual white balance red gain',
				name: 'Direct',
				bytes: [129, 1, 4, 67, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'gain',
						label: 'Manual red gain',
						min: 0,
						max: 16,
						nibbles: [13, 15],
						default: 8,
					},
				],
			},
		],
	},
	{
		id: 'manual_blue_gain',
		name: 'Manual white balance blue gain',
		commands: [
			{
				id: 'r40',
				groupId: 'manual_blue_gain',
				groupName: 'Manual white balance blue gain',
				name: 'Reset',
				bytes: [129, 1, 4, 4, 0, 255],
				parameters: [],
			},
			{
				id: 'r41',
				groupId: 'manual_blue_gain',
				groupName: 'Manual white balance blue gain',
				name: 'Up',
				bytes: [129, 1, 4, 4, 2, 255],
				parameters: [],
			},
			{
				id: 'r42',
				groupId: 'manual_blue_gain',
				groupName: 'Manual white balance blue gain',
				name: 'Down',
				bytes: [129, 1, 4, 4, 3, 255],
				parameters: [],
			},
			{
				id: 'r43',
				groupId: 'manual_blue_gain',
				groupName: 'Manual white balance blue gain',
				name: 'Direct',
				bytes: [129, 1, 4, 68, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'gain',
						label: 'Manual blue gain',
						min: 0,
						max: 16,
						nibbles: [13, 15],
						default: 8,
					},
				],
			},
		],
	},
	{
		id: 'automatic_red_gain',
		name: 'Automatic white balance red gain',
		commands: [
			{
				id: 'r44',
				groupId: 'automatic_red_gain',
				groupName: 'Automatic white balance red gain',
				name: 'Direct',
				bytes: [129, 1, 14, 36, 70, 0, 0, 255],
				parameters: [
					{
						id: 'gain',
						label: 'Automatic red gain',
						min: 0,
						max: 14,
						nibbles: [11, 13],
						default: 7,
					},
				],
			},
		],
	},
	{
		id: 'automatic_blue_gain',
		name: 'Automatic white balance blue gain',
		commands: [
			{
				id: 'r45',
				groupId: 'automatic_blue_gain',
				groupName: 'Automatic white balance blue gain',
				name: 'Direct',
				bytes: [129, 1, 14, 36, 71, 0, 0, 255],
				parameters: [
					{
						id: 'gain',
						label: 'Automatic blue gain',
						min: 0,
						max: 14,
						nibbles: [11, 13],
						default: 7,
					},
				],
			},
		],
	},
	{
		id: 'automatic_green_gain',
		name: 'Automatic white balance green gain',
		commands: [
			{
				id: 'r46',
				groupId: 'automatic_green_gain',
				groupName: 'Automatic white balance green gain',
				name: 'Direct',
				bytes: [129, 1, 14, 36, 72, 0, 0, 255],
				parameters: [
					{
						id: 'gain',
						label: 'Automatic green gain',
						min: 0,
						max: 14,
						nibbles: [11, 13],
						default: 7,
					},
				],
			},
		],
	},
	{
		id: 'exposure_mode',
		name: 'Exposure mode',
		commands: [
			{
				id: 'r47',
				groupId: 'exposure_mode',
				groupName: 'Exposure mode',
				name: 'Full Auto',
				bytes: [129, 1, 4, 57, 0, 255],
				parameters: [],
			},
			{
				id: 'r48',
				groupId: 'exposure_mode',
				groupName: 'Exposure mode',
				name: 'Manual',
				bytes: [129, 1, 4, 57, 3, 255],
				parameters: [],
			},
			{
				id: 'r49',
				groupId: 'exposure_mode',
				groupName: 'Exposure mode',
				name: 'Shutter Priority',
				bytes: [129, 1, 4, 57, 10, 255],
				parameters: [],
			},
			{
				id: 'r50',
				groupId: 'exposure_mode',
				groupName: 'Exposure mode',
				name: 'Iris Priority',
				bytes: [129, 1, 4, 57, 11, 255],
				parameters: [],
			},
			{
				id: 'r51',
				groupId: 'exposure_mode',
				groupName: 'Exposure mode',
				name: 'Bright',
				bytes: [129, 1, 4, 57, 13, 255],
				parameters: [],
			},
			{
				id: 'r52',
				groupId: 'exposure_mode',
				groupName: 'Exposure mode',
				name: 'GainLimit',
				bytes: [129, 1, 4, 44, 0, 255],
				parameters: [
					{
						id: 'limit',
						label: 'Gain limit index (12–45 dB in 3 dB steps)',
						min: 4,
						max: 15,
						nibbles: [9],
						default: 15,
					},
				],
			},
		],
	},
	{
		id: 'shutter',
		name: 'Shutter',
		commands: [
			{
				id: 'r53',
				groupId: 'shutter',
				groupName: 'Shutter',
				name: 'Reset',
				bytes: [129, 1, 4, 10, 0, 255],
				parameters: [],
			},
			{
				id: 'r54',
				groupId: 'shutter',
				groupName: 'Shutter',
				name: 'Up',
				bytes: [129, 1, 4, 10, 2, 255],
				parameters: [],
			},
			{
				id: 'r55',
				groupId: 'shutter',
				groupName: 'Shutter',
				name: 'Down',
				bytes: [129, 1, 4, 10, 3, 255],
				parameters: [],
			},
			{
				id: 'r56',
				groupId: 'shutter',
				groupName: 'Shutter',
				name: 'Direct',
				bytes: [129, 1, 4, 74, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'position',
						label: 'Shutter position',
						min: 6,
						max: 21,
						nibbles: [13, 15],
						default: 8,
					},
				],
			},
		],
	},
	{
		id: 'iris',
		name: 'Iris',
		commands: [
			{
				id: 'r57',
				groupId: 'iris',
				groupName: 'Iris',
				name: 'Reset',
				bytes: [129, 1, 4, 11, 0, 255],
				parameters: [],
			},
			{
				id: 'r58',
				groupId: 'iris',
				groupName: 'Iris',
				name: 'Up',
				bytes: [129, 1, 4, 11, 2, 255],
				parameters: [],
			},
			{
				id: 'r59',
				groupId: 'iris',
				groupName: 'Iris',
				name: 'Down',
				bytes: [129, 1, 4, 11, 3, 255],
				parameters: [],
			},
			{
				id: 'r60',
				groupId: 'iris',
				groupName: 'Iris',
				name: 'Direct',
				bytes: [129, 1, 4, 75, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'position',
						label: 'Iris position',
						min: 0,
						max: 13,
						nibbles: [13, 15],
						default: 8,
					},
				],
			},
		],
	},
	{
		id: 'gain',
		name: 'Gain',
		commands: [
			{
				id: 'r61',
				groupId: 'gain',
				groupName: 'Gain',
				name: 'Reset',
				bytes: [129, 1, 4, 12, 0, 255],
				parameters: [],
			},
			{
				id: 'r62',
				groupId: 'gain',
				groupName: 'Gain',
				name: 'Up',
				bytes: [129, 1, 4, 12, 2, 255],
				parameters: [],
			},
			{
				id: 'r63',
				groupId: 'gain',
				groupName: 'Gain',
				name: 'Down',
				bytes: [129, 1, 4, 12, 3, 255],
				parameters: [],
			},
			{
				id: 'r64',
				groupId: 'gain',
				groupName: 'Gain',
				name: 'Direct',
				bytes: [129, 1, 4, 76, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'position',
						label: 'Gain position',
						min: 0,
						max: 14,
						nibbles: [13, 15],
						default: 0,
					},
				],
			},
		],
	},
	{
		id: 'bright',
		name: 'Exposure brightness',
		commands: [
			{
				id: 'r65',
				groupId: 'bright',
				groupName: 'Exposure brightness',
				name: 'Reset',
				bytes: [129, 1, 4, 13, 0, 255],
				parameters: [],
			},
			{
				id: 'r66',
				groupId: 'bright',
				groupName: 'Exposure brightness',
				name: 'Up',
				bytes: [129, 1, 4, 13, 2, 255],
				parameters: [],
			},
			{
				id: 'r67',
				groupId: 'bright',
				groupName: 'Exposure brightness',
				name: 'Down',
				bytes: [129, 1, 4, 13, 3, 255],
				parameters: [],
			},
			{
				id: 'r68',
				groupId: 'bright',
				groupName: 'Exposure brightness',
				name: 'Direct',
				bytes: [129, 1, 4, 77, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'position',
						label: 'Brightness position',
						min: 0,
						max: 27,
						nibbles: [13, 15],
						default: 13,
					},
				],
			},
		],
	},
	{
		id: 'exposure_compensation',
		name: 'Exposure compensation',
		commands: [
			{
				id: 'r69',
				groupId: 'exposure_compensation',
				groupName: 'Exposure compensation',
				name: 'On',
				bytes: [129, 1, 4, 62, 2, 255],
				parameters: [],
			},
			{
				id: 'r70',
				groupId: 'exposure_compensation',
				groupName: 'Exposure compensation',
				name: 'Off',
				bytes: [129, 1, 4, 62, 3, 255],
				parameters: [],
			},
			{
				id: 'r71',
				groupId: 'exposure_compensation',
				groupName: 'Exposure compensation',
				name: 'Reset',
				bytes: [129, 1, 4, 14, 0, 255],
				parameters: [],
			},
			{
				id: 'r72',
				groupId: 'exposure_compensation',
				groupName: 'Exposure compensation',
				name: 'Up',
				bytes: [129, 1, 4, 14, 2, 255],
				parameters: [],
			},
			{
				id: 'r73',
				groupId: 'exposure_compensation',
				groupName: 'Exposure compensation',
				name: 'Down',
				bytes: [129, 1, 4, 14, 3, 255],
				parameters: [],
			},
			{
				id: 'r74',
				groupId: 'exposure_compensation',
				groupName: 'Exposure compensation',
				name: 'Direct',
				bytes: [129, 1, 4, 78, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'position',
						label: 'Exposure compensation',
						min: 0,
						max: 14,
						nibbles: [13, 15],
						default: 7,
						choices: [
							{
								value: 0,
								label: '-7',
							},
							{
								value: 1,
								label: '-6',
							},
							{
								value: 2,
								label: '-5',
							},
							{
								value: 3,
								label: '-4',
							},
							{
								value: 4,
								label: '-3',
							},
							{
								value: 5,
								label: '-2',
							},
							{
								value: 6,
								label: '-1',
							},
							{
								value: 7,
								label: '0',
							},
							{
								value: 8,
								label: '1',
							},
							{
								value: 9,
								label: '2',
							},
							{
								value: 10,
								label: '3',
							},
							{
								value: 11,
								label: '4',
							},
							{
								value: 12,
								label: '5',
							},
							{
								value: 13,
								label: '6',
							},
							{
								value: 14,
								label: '7',
							},
						],
					},
				],
			},
		],
	},
	{
		id: 'backlight',
		name: 'Backlight compensation',
		commands: [
			{
				id: 'r75',
				groupId: 'backlight',
				groupName: 'Backlight compensation',
				name: 'On',
				bytes: [129, 1, 4, 51, 2, 255],
				parameters: [],
			},
			{
				id: 'r76',
				groupId: 'backlight',
				groupName: 'Backlight compensation',
				name: 'Off',
				bytes: [129, 1, 4, 51, 3, 255],
				parameters: [],
			},
		],
	},
	{
		id: 'aperture',
		name: 'Aperture',
		commands: [
			{
				id: 'r77',
				groupId: 'aperture',
				groupName: 'Aperture',
				name: 'Reset',
				bytes: [129, 1, 4, 2, 0, 255],
				parameters: [],
			},
			{
				id: 'r78',
				groupId: 'aperture',
				groupName: 'Aperture',
				name: 'Up',
				bytes: [129, 1, 4, 2, 2, 255],
				parameters: [],
			},
			{
				id: 'r79',
				groupId: 'aperture',
				groupName: 'Aperture',
				name: 'Down',
				bytes: [129, 1, 4, 2, 3, 255],
				parameters: [],
			},
			{
				id: 'r80',
				groupId: 'aperture',
				groupName: 'Aperture',
				name: 'Direct',
				bytes: [129, 1, 4, 66, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'gain',
						label: 'Aperture gain',
						min: 0,
						max: 11,
						nibbles: [13, 15],
						default: 5,
					},
				],
			},
		],
	},
	{
		id: 'memory',
		name: 'Preset memory',
		commands: [
			{
				id: 'r81',
				groupId: 'memory',
				groupName: 'Preset memory',
				name: 'Reset',
				bytes: [129, 1, 4, 63, 0, 0, 255],
				parameters: [
					{
						id: 'preset',
						label: 'Preset number',
						min: 0,
						max: 64,
						nibbles: [10, 11],
						default: 0,
					},
				],
			},
			{
				id: 'r82',
				groupId: 'memory',
				groupName: 'Preset memory',
				name: 'Set',
				bytes: [129, 1, 4, 63, 1, 0, 255],
				parameters: [
					{
						id: 'preset',
						label: 'Preset number',
						min: 0,
						max: 64,
						nibbles: [10, 11],
						default: 0,
					},
				],
			},
			{
				id: 'r83',
				groupId: 'memory',
				groupName: 'Preset memory',
				name: 'Recall',
				bytes: [129, 1, 4, 63, 2, 0, 255],
				parameters: [
					{
						id: 'preset',
						label: 'Preset number',
						min: 0,
						max: 64,
						nibbles: [10, 11],
						default: 0,
					},
				],
			},
		],
	},
	{
		id: 'ir_receive',
		name: 'IR receiver',
		commands: [
			{
				id: 'r84',
				groupId: 'ir_receive',
				groupName: 'IR receiver',
				name: 'ON',
				bytes: [129, 1, 6, 8, 2, 255],
				parameters: [],
			},
			{
				id: 'r85',
				groupId: 'ir_receive',
				groupName: 'IR receiver',
				name: 'OFF',
				bytes: [129, 1, 6, 8, 3, 255],
				parameters: [],
			},
			{
				id: 'r86',
				groupId: 'ir_receive',
				groupName: 'IR receiver',
				name: 'ON/OFF',
				bytes: [129, 1, 6, 8, 16, 255],
				parameters: [],
			},
		],
	},
	{
		id: 'video_system',
		name: 'Video format',
		commands: [
			{
				id: 'r87',
				groupId: 'video_system',
				groupName: 'Video format',
				name: '60 HZ',
				bytes: [129, 1, 6, 53, 0, 0, 255],
				parameters: [],
			},
			{
				id: 'r88',
				groupId: 'video_system',
				groupName: 'Video format',
				name: '1920 x1080p',
				bytes: [129, 1, 6, 53, 0, 1, 255],
				parameters: [],
			},
			{
				id: 'r89',
				groupId: 'video_system',
				groupName: 'Video format',
				name: '1280 x720p',
				bytes: [129, 1, 6, 53, 0, 3, 255],
				parameters: [],
			},
			{
				id: 'r90',
				groupId: 'video_system',
				groupName: 'Video format',
				name: '50 HZ',
				bytes: [129, 1, 6, 53, 0, 8, 255],
				parameters: [],
			},
			{
				id: 'r91',
				groupId: 'video_system',
				groupName: 'Video format',
				name: '1920 x1080p',
				bytes: [129, 1, 6, 53, 0, 9, 255],
				parameters: [],
			},
			{
				id: 'r92',
				groupId: 'video_system',
				groupName: 'Video format',
				name: '1280 x720p',
				bytes: [129, 1, 6, 53, 0, 11, 255],
				parameters: [],
			},
			{
				id: 'r93',
				groupId: 'video_system',
				groupName: 'Video format',
				name: '1280 x720p',
				bytes: [129, 1, 6, 53, 0, 12, 255],
				parameters: [],
			},
			{
				id: 'r94',
				groupId: 'video_system',
				groupName: 'Video format',
				name: '59.94/29.97',
				bytes: [129, 1, 6, 53, 0, 16, 255],
				parameters: [],
			},
			{
				id: 'r95',
				groupId: 'video_system',
				groupName: 'Video format',
				name: '1920 x1080p',
				bytes: [129, 1, 6, 53, 0, 17, 255],
				parameters: [],
			},
			{
				id: 'r96',
				groupId: 'video_system',
				groupName: 'Video format',
				name: '1280 x720p',
				bytes: [129, 1, 6, 53, 0, 18, 255],
				parameters: [],
			},
		],
	},
	{
		id: 'pan_tilt',
		name: 'Pan and tilt',
		commands: [
			{
				id: 'r97',
				groupId: 'pan_tilt',
				groupName: 'Pan and tilt',
				name: 'Up',
				bytes: [129, 1, 6, 1, 0, 0, 3, 1, 255],
				parameters: [
					{
						id: 'pan_speed',
						label: 'Pan speed',
						min: 1,
						max: 24,
						nibbles: [8, 9],
						default: 12,
					},
					{
						id: 'tilt_speed',
						label: 'Tilt speed',
						min: 1,
						max: 20,
						nibbles: [10, 11],
						default: 12,
					},
				],
			},
			{
				id: 'r98',
				groupId: 'pan_tilt',
				groupName: 'Pan and tilt',
				name: 'Down',
				bytes: [129, 1, 6, 1, 0, 0, 3, 2, 255],
				parameters: [
					{
						id: 'pan_speed',
						label: 'Pan speed',
						min: 1,
						max: 24,
						nibbles: [8, 9],
						default: 12,
					},
					{
						id: 'tilt_speed',
						label: 'Tilt speed',
						min: 1,
						max: 20,
						nibbles: [10, 11],
						default: 12,
					},
				],
			},
			{
				id: 'r99',
				groupId: 'pan_tilt',
				groupName: 'Pan and tilt',
				name: 'Left',
				bytes: [129, 1, 6, 1, 0, 0, 1, 3, 255],
				parameters: [
					{
						id: 'pan_speed',
						label: 'Pan speed',
						min: 1,
						max: 24,
						nibbles: [8, 9],
						default: 12,
					},
					{
						id: 'tilt_speed',
						label: 'Tilt speed',
						min: 1,
						max: 20,
						nibbles: [10, 11],
						default: 12,
					},
				],
			},
			{
				id: 'r100',
				groupId: 'pan_tilt',
				groupName: 'Pan and tilt',
				name: 'Right',
				bytes: [129, 1, 6, 1, 0, 0, 2, 3, 255],
				parameters: [
					{
						id: 'pan_speed',
						label: 'Pan speed',
						min: 1,
						max: 24,
						nibbles: [8, 9],
						default: 12,
					},
					{
						id: 'tilt_speed',
						label: 'Tilt speed',
						min: 1,
						max: 20,
						nibbles: [10, 11],
						default: 12,
					},
				],
			},
			{
				id: 'r101',
				groupId: 'pan_tilt',
				groupName: 'Pan and tilt',
				name: 'UpLeft',
				bytes: [129, 1, 6, 1, 0, 0, 1, 1, 255],
				parameters: [
					{
						id: 'pan_speed',
						label: 'Pan speed',
						min: 1,
						max: 24,
						nibbles: [8, 9],
						default: 12,
					},
					{
						id: 'tilt_speed',
						label: 'Tilt speed',
						min: 1,
						max: 20,
						nibbles: [10, 11],
						default: 12,
					},
				],
			},
			{
				id: 'r102',
				groupId: 'pan_tilt',
				groupName: 'Pan and tilt',
				name: 'UpRight',
				bytes: [129, 1, 6, 1, 0, 0, 2, 1, 255],
				parameters: [
					{
						id: 'pan_speed',
						label: 'Pan speed',
						min: 1,
						max: 24,
						nibbles: [8, 9],
						default: 12,
					},
					{
						id: 'tilt_speed',
						label: 'Tilt speed',
						min: 1,
						max: 20,
						nibbles: [10, 11],
						default: 12,
					},
				],
			},
			{
				id: 'r103',
				groupId: 'pan_tilt',
				groupName: 'Pan and tilt',
				name: 'DownLeft',
				bytes: [129, 1, 6, 1, 0, 0, 1, 2, 255],
				parameters: [
					{
						id: 'pan_speed',
						label: 'Pan speed',
						min: 1,
						max: 24,
						nibbles: [8, 9],
						default: 12,
					},
					{
						id: 'tilt_speed',
						label: 'Tilt speed',
						min: 1,
						max: 20,
						nibbles: [10, 11],
						default: 12,
					},
				],
			},
			{
				id: 'r104',
				groupId: 'pan_tilt',
				groupName: 'Pan and tilt',
				name: 'DownRight',
				bytes: [129, 1, 6, 1, 0, 0, 2, 2, 255],
				parameters: [
					{
						id: 'pan_speed',
						label: 'Pan speed',
						min: 1,
						max: 24,
						nibbles: [8, 9],
						default: 12,
					},
					{
						id: 'tilt_speed',
						label: 'Tilt speed',
						min: 1,
						max: 20,
						nibbles: [10, 11],
						default: 12,
					},
				],
			},
			{
				id: 'r105',
				groupId: 'pan_tilt',
				groupName: 'Pan and tilt',
				name: 'Stop',
				bytes: [129, 1, 6, 1, 0, 0, 3, 3, 255],
				parameters: [
					{
						id: 'pan_speed',
						label: 'Pan speed',
						min: 1,
						max: 24,
						nibbles: [8, 9],
						default: 12,
					},
					{
						id: 'tilt_speed',
						label: 'Tilt speed',
						min: 1,
						max: 20,
						nibbles: [10, 11],
						default: 12,
					},
				],
			},
			{
				id: 'r106',
				groupId: 'pan_tilt',
				groupName: 'Pan and tilt',
				name: 'AbsolutePosition',
				bytes: [129, 1, 6, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'pan_speed',
						label: 'Pan speed',
						min: 1,
						max: 24,
						nibbles: [8, 9],
						default: 12,
					},
					{
						id: 'tilt_speed',
						label: 'Tilt speed',
						min: 1,
						max: 20,
						nibbles: [10, 11],
						default: 12,
					},
					{
						id: 'pan_position',
						label: 'Pan position',
						min: 0,
						max: 65535,
						nibbles: [13, 15, 17, 19],
						default: 0,
					},
					{
						id: 'tilt_position',
						label: 'Tilt position',
						min: 0,
						max: 65535,
						nibbles: [21, 23, 25, 27],
						default: 0,
					},
				],
			},
			{
				id: 'r107',
				groupId: 'pan_tilt',
				groupName: 'Pan and tilt',
				name: 'RelativePosition',
				bytes: [129, 1, 6, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'pan_speed',
						label: 'Pan speed',
						min: 1,
						max: 24,
						nibbles: [8, 9],
						default: 12,
					},
					{
						id: 'tilt_speed',
						label: 'Tilt speed',
						min: 1,
						max: 20,
						nibbles: [10, 11],
						default: 12,
					},
					{
						id: 'pan_offset',
						label: 'Pan offset',
						min: 0,
						max: 65535,
						nibbles: [13, 15, 17, 19],
						default: 0,
					},
					{
						id: 'tilt_offset',
						label: 'Tilt offset',
						min: 0,
						max: 65535,
						nibbles: [21, 23, 25, 27],
						default: 0,
					},
				],
			},
			{
				id: 'r108',
				groupId: 'pan_tilt',
				groupName: 'Pan and tilt',
				name: 'Home',
				bytes: [129, 1, 6, 4, 255],
				parameters: [],
			},
			{
				id: 'r109',
				groupId: 'pan_tilt',
				groupName: 'Pan and tilt',
				name: 'Reset',
				bytes: [129, 1, 6, 5, 255],
				parameters: [],
			},
		],
	},
	{
		id: 'audio_volume',
		name: 'Audio volume',
		commands: [
			{
				id: 'r110',
				groupId: 'audio_volume',
				groupName: 'Audio volume',
				name: 'Reset',
				bytes: [129, 1, 4, 110, 0, 255],
				parameters: [],
			},
			{
				id: 'r111',
				groupId: 'audio_volume',
				groupName: 'Audio volume',
				name: 'Up',
				bytes: [129, 1, 4, 110, 2, 255],
				parameters: [],
			},
			{
				id: 'r112',
				groupId: 'audio_volume',
				groupName: 'Audio volume',
				name: 'Down',
				bytes: [129, 1, 4, 110, 3, 255],
				parameters: [],
			},
			{
				id: 'r113',
				groupId: 'audio_volume',
				groupName: 'Audio volume',
				name: 'Direct',
				bytes: [129, 1, 4, 110, 1, 0, 0, 255],
				parameters: [
					{
						id: 'volume',
						label: 'Audio volume',
						min: 0,
						max: 100,
						nibbles: [11, 13],
						default: 50,
					},
				],
			},
		],
	},
	{
		id: 'sharpness',
		name: 'Image sharpness',
		commands: [
			{
				id: 'r114',
				groupId: 'sharpness',
				groupName: 'Image sharpness',
				name: 'Direct',
				bytes: [129, 1, 14, 36, 64, 0, 0, 255],
				parameters: [
					{
						id: 'value',
						label: 'Sharpness',
						min: 0,
						max: 11,
						nibbles: [11, 13],
						default: 5,
					},
				],
			},
		],
	},
	{
		id: 'brightness',
		name: 'Image brightness',
		commands: [
			{
				id: 'r115',
				groupId: 'brightness',
				groupName: 'Image brightness',
				name: 'Direct',
				bytes: [129, 1, 14, 36, 65, 0, 0, 255],
				parameters: [
					{
						id: 'value',
						label: 'Brightness',
						min: 0,
						max: 14,
						nibbles: [11, 13],
						default: 7,
					},
				],
			},
		],
	},
	{
		id: 'contrast',
		name: 'Image contrast',
		commands: [
			{
				id: 'r116',
				groupId: 'contrast',
				groupName: 'Image contrast',
				name: 'Direct',
				bytes: [129, 1, 14, 36, 66, 0, 0, 255],
				parameters: [
					{
						id: 'value',
						label: 'Contrast',
						min: 0,
						max: 14,
						nibbles: [11, 13],
						default: 7,
					},
				],
			},
		],
	},
	{
		id: 'saturation',
		name: 'Image saturation',
		commands: [
			{
				id: 'r117',
				groupId: 'saturation',
				groupName: 'Image saturation',
				name: 'Direct',
				bytes: [129, 1, 14, 36, 67, 0, 0, 255],
				parameters: [
					{
						id: 'value',
						label: 'Saturation',
						min: 0,
						max: 14,
						nibbles: [11, 13],
						default: 7,
					},
				],
			},
		],
	},
	{
		id: 'hue',
		name: 'Image hue',
		commands: [
			{
				id: 'r118',
				groupId: 'hue',
				groupName: 'Image hue',
				name: 'Direct',
				bytes: [129, 1, 14, 36, 68, 0, 0, 255],
				parameters: [
					{
						id: 'value',
						label: 'Hue',
						min: 0,
						max: 14,
						nibbles: [11, 13],
						default: 7,
					},
				],
			},
		],
	},
	{
		id: 'noise_reduction_2d',
		name: '2D noise reduction',
		commands: [
			{
				id: 'r119',
				groupId: 'noise_reduction_2d',
				groupName: '2D noise reduction',
				name: 'Direct',
				bytes: [129, 1, 4, 83, 0, 255],
				parameters: [
					{
						id: 'value',
						label: '2D noise reduction',
						min: 0,
						max: 7,
						nibbles: [9],
						default: 3,
					},
				],
			},
		],
	},
	{
		id: 'noise_reduction_3d',
		name: '3D noise reduction',
		commands: [
			{
				id: 'r120',
				groupId: 'noise_reduction_3d',
				groupName: '3D noise reduction',
				name: 'Direct',
				bytes: [129, 1, 4, 84, 0, 255],
				parameters: [
					{
						id: 'value',
						label: '3D noise reduction',
						min: 0,
						max: 7,
						nibbles: [9],
						default: 3,
					},
				],
			},
		],
	},
	{
		id: 'gamma',
		name: 'Gamma',
		commands: [
			{
				id: 'r121',
				groupId: 'gamma',
				groupName: 'Gamma',
				name: 'Direct',
				bytes: [129, 1, 4, 91, 0, 255],
				parameters: [
					{
						id: 'value',
						label: 'Gamma',
						min: 0,
						max: 4,
						nibbles: [9],
						default: 2,
					},
				],
			},
		],
	},
	{
		id: 'wdr',
		name: 'Wide dynamic range',
		commands: [
			{
				id: 'r122',
				groupId: 'wdr',
				groupName: 'Wide dynamic range',
				name: 'Direct',
				bytes: [129, 1, 4, 61, 0, 255],
				parameters: [
					{
						id: 'value',
						label: 'Wide dynamic range',
						min: 0,
						max: 5,
						nibbles: [9],
						default: 0,
					},
				],
			},
		],
	},
	{
		id: 'mirror',
		name: 'Mirror',
		commands: [
			{
				id: 'r123',
				groupId: 'mirror',
				groupName: 'Mirror',
				name: 'Direct',
				bytes: [129, 1, 4, 97, 0, 255],
				parameters: [
					{
						id: 'state',
						label: 'Mirror',
						min: 2,
						max: 3,
						nibbles: [9],
						default: 3,
						choices: [
							{
								value: 2,
								label: 'On',
							},
							{
								value: 3,
								label: 'Off',
							},
						],
					},
				],
			},
		],
	},
	{
		id: 'flip',
		name: 'Flip',
		commands: [
			{
				id: 'r124',
				groupId: 'flip',
				groupName: 'Flip',
				name: 'Direct',
				bytes: [129, 1, 4, 102, 0, 255],
				parameters: [
					{
						id: 'state',
						label: 'Flip',
						min: 2,
						max: 3,
						nibbles: [9],
						default: 3,
						choices: [
							{
								value: 2,
								label: 'On',
							},
							{
								value: 3,
								label: 'Off',
							},
						],
					},
				],
			},
		],
	},
	{
		id: 'anti_flicker',
		name: 'Anti-flicker',
		commands: [
			{
				id: 'r125',
				groupId: 'anti_flicker',
				groupName: 'Anti-flicker',
				name: 'Direct',
				bytes: [129, 1, 4, 58, 0, 255],
				parameters: [
					{
						id: 'mode',
						label: 'Anti-flicker mode',
						min: 0,
						max: 2,
						nibbles: [9],
						default: 0,
						choices: [
							{
								value: 0,
								label: 'Off',
							},
							{
								value: 1,
								label: '50 Hz',
							},
							{
								value: 2,
								label: '60 Hz',
							},
						],
					},
				],
			},
		],
	},
	{
		id: 'dhcp',
		name: 'Network DHCP',
		commands: [
			{
				id: 'r126',
				groupId: 'dhcp',
				groupName: 'Network DHCP',
				name: 'On',
				bytes: [129, 1, 8, 8, 2, 255],
				parameters: [],
			},
			{
				id: 'r127',
				groupId: 'dhcp',
				groupName: 'Network DHCP',
				name: 'Off',
				bytes: [129, 1, 8, 8, 3, 255],
				parameters: [],
			},
		],
	},
	{
		id: 'ip_address',
		name: 'Network IP address',
		commands: [
			{
				id: 'r128',
				groupId: 'ip_address',
				groupName: 'Network IP address',
				name: 'Set address',
				bytes: [129, 1, 8, 7, 1, 0, 0, 0, 0, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'octet_1',
						label: 'IP address octet 1',
						min: 0,
						max: 255,
						nibbles: [11, 13],
						default: 192,
					},
					{
						id: 'octet_2',
						label: 'IP address octet 2',
						min: 0,
						max: 255,
						nibbles: [15, 17],
						default: 168,
					},
					{
						id: 'octet_3',
						label: 'IP address octet 3',
						min: 0,
						max: 255,
						nibbles: [19, 21],
						default: 1,
					},
					{
						id: 'octet_4',
						label: 'IP address octet 4',
						min: 0,
						max: 255,
						nibbles: [23, 25],
						default: 100,
					},
				],
			},
		],
	},
	{
		id: 'ip_mask',
		name: 'Network subnet mask',
		commands: [
			{
				id: 'r129',
				groupId: 'ip_mask',
				groupName: 'Network subnet mask',
				name: 'Set subnet mask',
				bytes: [129, 1, 8, 7, 2, 0, 0, 0, 0, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'octet_1',
						label: 'Subnet mask octet 1',
						min: 0,
						max: 255,
						nibbles: [11, 13],
						default: 255,
					},
					{
						id: 'octet_2',
						label: 'Subnet mask octet 2',
						min: 0,
						max: 255,
						nibbles: [15, 17],
						default: 255,
					},
					{
						id: 'octet_3',
						label: 'Subnet mask octet 3',
						min: 0,
						max: 255,
						nibbles: [19, 21],
						default: 255,
					},
					{
						id: 'octet_4',
						label: 'Subnet mask octet 4',
						min: 0,
						max: 255,
						nibbles: [23, 25],
						default: 0,
					},
				],
			},
		],
	},
	{
		id: 'ip_gateway',
		name: 'Network gateway',
		commands: [
			{
				id: 'r130',
				groupId: 'ip_gateway',
				groupName: 'Network gateway',
				name: 'Set gateway',
				bytes: [129, 1, 8, 7, 3, 0, 0, 0, 0, 0, 0, 0, 0, 255],
				parameters: [
					{
						id: 'octet_1',
						label: 'Gateway octet 1',
						min: 0,
						max: 255,
						nibbles: [11, 13],
						default: 192,
					},
					{
						id: 'octet_2',
						label: 'Gateway octet 2',
						min: 0,
						max: 255,
						nibbles: [15, 17],
						default: 168,
					},
					{
						id: 'octet_3',
						label: 'Gateway octet 3',
						min: 0,
						max: 255,
						nibbles: [19, 21],
						default: 1,
					},
					{
						id: 'octet_4',
						label: 'Gateway octet 4',
						min: 0,
						max: 255,
						nibbles: [23, 25],
						default: 1,
					},
				],
			},
		],
	},
	{
		id: 'apply_ip',
		name: 'Apply network settings',
		commands: [
			{
				id: 'r131',
				groupId: 'apply_ip',
				groupName: 'Apply network settings',
				name: 'Apply settings',
				bytes: [129, 1, 8, 7, 9, 255],
				parameters: [],
			},
		],
	},
	{
		id: 'factory_reset',
		name: 'Factory reset',
		commands: [
			{
				id: 'r132',
				groupId: 'factory_reset',
				groupName: 'Factory reset',
				name: 'Restore factory settings',
				bytes: [129, 1, 4, 63, 3, 0, 255],
				parameters: [],
			},
		],
	},
	{
		id: 'system_menu',
		name: 'System menu',
		commands: [
			{
				id: 'r133',
				groupId: 'system_menu',
				groupName: 'System menu',
				name: 'Direct',
				bytes: [129, 1, 6, 6, 16, 255],
				parameters: [],
			},
			{
				id: 'r134',
				groupId: 'system_menu',
				groupName: 'System menu',
				name: 'ON',
				bytes: [129, 1, 6, 6, 2, 255],
				parameters: [],
			},
			{
				id: 'r135',
				groupId: 'system_menu',
				groupName: 'System menu',
				name: 'OFF',
				bytes: [129, 1, 6, 6, 3, 255],
				parameters: [],
			},
			{
				id: 'r136',
				groupId: 'system_menu',
				groupName: 'System menu',
				name: 'ENTER',
				bytes: [129, 1, 4, 7, 2, 255],
				parameters: [],
			},
			{
				id: 'r137',
				groupId: 'system_menu',
				groupName: 'System menu',
				name: 'RETURN',
				bytes: [129, 1, 4, 7, 3, 255],
				parameters: [],
			},
		],
	},
	{
		id: 'tally',
		name: 'Tally light',
		commands: [
			{
				id: 'r138',
				groupId: 'tally',
				groupName: 'Tally light',
				name: 'Green on',
				bytes: [129, 1, 8, 0, 2, 255],
				parameters: [],
			},
			{
				id: 'r139',
				groupId: 'tally',
				groupName: 'Tally light',
				name: 'Red on',
				bytes: [129, 1, 8, 1, 2, 255],
				parameters: [],
			},
			{
				id: 'r140',
				groupId: 'tally',
				groupName: 'Tally light',
				name: 'Green and red on',
				bytes: [129, 1, 8, 2, 2, 255],
				parameters: [],
			},
			{
				id: 'r141',
				groupId: 'tally',
				groupName: 'Tally light',
				name: 'All off',
				bytes: [129, 1, 8, 2, 3, 255],
				parameters: [],
			},
			{
				id: 'r142',
				groupId: 'tally',
				groupName: 'Tally light',
				name: 'Green flash',
				bytes: [129, 1, 8, 16, 2, 255],
				parameters: [],
			},
			{
				id: 'r143',
				groupId: 'tally',
				groupName: 'Tally light',
				name: 'Red flash',
				bytes: [129, 1, 8, 17, 2, 255],
				parameters: [],
			},
		],
	},
] as const satisfies readonly Lv20nCommandGroup[]
